#ifndef SEGGER_SYSVIEW_CONF_H
#define SEGGER_SYSVIEW_CONF_H

#define SEGGER_SYSVIEW_RTT_CHANNEL     1
#define SEGGER_SYSVIEW_RTT_BUFFER_SIZE 8192
#define SEGGER_SYSVIEW_TIMESTAMP_BITS 32
#define SEGGER_SYSVIEW_ON_EVENT_RECORDED(n) SEGGER_SYSVIEW_X_OnEventRecorded(n)

#endif
