#ifndef APP_TRAX_CONFIG_H
#define APP_TRAX_CONFIG_H

#include "app_trace_config.h"
#include "stm32f7xx.h"

#define TRAX_ENABLE (APP_TRACE_BACKEND == APP_TRACE_TRAXCOPE)
#define TRAX_CFG_HW_PORT TRAX_HW_PORT_ARM_CORTEX_M
#define TRAX_CFG_RTOS_TYPE TRAX_RTOS_FREERTOS
#define TRAX_CFG_FREERTOS_VERSION TRAX_FREERTOS_VERSION(10, 2, 0)

/* FreeRTOS SysTick: 216 MHz core clock, 1 kHz tick. HAL uses TIM6. */
#define TRAX_CFG_TIMESTAMP_MODE TRAX_TIMESTAMP_TICK_TIMER
#define TRAX_CFG_TIMESTAMP_TIMER_VAL (SysTick->VAL)
#define TRAX_CFG_TIMESTAMP_TIMER_DIR TRAX_TIMER_DIR_DOWN
#define TRAX_CFG_TIMER_FREQ_HZ 216000000U
#define TRAX_CFG_TICK_COUNTER_PERIOD 216000U

#define TRAX_CFG_TRANSPORT TRAX_TRANSPORT_CUSTOM
#define TRAX_CFG_TRANSPORT_TX_FREE App_Traxcope_TxFree
#define TRAX_CFG_TRANSPORT_BUF_SIZE 8192U
#define TRAX_CFG_TX_BATCH_MAX_BYTES 1024U
/* Every frame must fit in the DMA staging buffer, including metadata. */
#define TRAX_CFG_FRAME_MAX_SIZE32 (TRAX_CFG_TRANSPORT_BUF_SIZE / 4U)
#define TRAX_CFG_OUT_BUFFER_SIZE32 4096U
#define TRAX_CFG_IN_BUFFER_SIZE32 64U
#define TRAX_CFG_STREAM_CNT 0

#define TRAX_CFG_MAX_RTOS_TASKS 16
#define TRAX_CFG_MAX_RTOS_OBJECTS 16
#define TRAX_CFG_RTOS_TASK_NAME_MAX 16
#define TRAX_CFG_CTRL_TASK_PRIORITY 1
#define TRAX_CFG_CTRL_TASK_STACK_SIZE 512
#define TRAX_CFG_CTRL_TASK_PERIOD_MS 1

#define TRAX_CFG_META_STORAGE TRAX_META_IN_FLASH
#define TRAX_CFG_PROJECT_NAME "RTOS Bootcamp STM32F746"
#define TRAX_CFG_BUILD_VERSION "USART6"

#endif
